# Generated by Django 4.2.5 on 2023-10-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsisScan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
